travis:
  secure:
    BINSTAR_TOKEN: q29yFUlgGv8sOwheHUlTTSYlLt9UpD6vFdSrnXh5FuH6kBciM1Iml532AHchVv7uXuDfPBMleTXUXo9RLuQwc/IFiyZX7GGrhaxQPk452esLYWezqFsLwOPYmwyglIluoALTbuPn0fzcN2HudjhzKE50VM8LiLogktTZPOovVXhK7PxerMl4ym2Nd/5iOWWR+aa+szxNdjVo1woKtqpytt86nduO2Uqj+rTh9DiYCvHtlntILX4cBYXJpRkOFTsc0LirT/oDBW6FpEjToab+CktSCzK1xX/JLJHV8BmiykHAhUyggqH84gzaiamY0DdjxGD1uH+zsT7PVZWYxyFsTmwcJxG8x4P5QVylpS+7WNcVlVCCVXFcUpcVy3wGG/h5Ze11WdLfIDTBzZQiKJ87u9DpeeAsMsoRfKe7XOYyNFeX+bBbIUw+D+RLNWB1xsX6vwiFlqvq4N5HdNrQP4FY3pUdbvzuicS7qE2luqeOcykPKJKPm/TSLv2RWTNmRxkDx3d+MNQRdI2yeR5PvEMxJKYStnEyfr/hVMgbgYdDbfS/s7AEe/YSJYBz6Acr1i9HJoDBQV6tFkJJ1Z3OE0SYwLD1XwK7CITPyM8k2e26IFao56k7JipDdi3y+0dcUc1zdChF10xcE1yafGmkFzIfJKoCwGbdK7ihJXsFnsu5pvI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
